# Generated by Django 2.2.8 on 2022-11-27 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
        ('shop', '0002_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='metadata.product_condition'),
        ),
    ]
