# Generated by Django 2.2.8 on 2022-12-13 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_product_status'),
        ('shop', '0002_auto_20221201_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='metadata.product_status'),
        ),
    ]
