# Generated by Django 2.2.8 on 2022-11-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20221130_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra_images',
            old_name='image',
            new_name='img',
        ),
    ]
