# Generated by Django 2.2.8 on 2022-12-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_condition'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'description'], name='shop_produc_name_3c8563_idx'),
        ),
    ]
