# Generated by Django 2.2.8 on 2022-11-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
    ]
