# Generated by Django 2.2.8 on 2022-12-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20221225_1956'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_name_3c8563_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'description'], name='text_index'),
        ),
    ]
